import type { Metadata } from "next";
// TODO update to Neue Montreal when possible
import { Inter } from "next/font/google";
import Wilden from "next/font/local";

import "./globals.css";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

const wilden = Wilden({
	src: "../fonts/Wilden/Wilden.ttf",
	display: "swap",
	variable: "--font-wilden",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${wilden.variable}`}>{children}</body>
		</html>
	);
}
